# Generated by Django 4.0.4 on 2022-06-28 07:46

import district.models.user
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import toolbox.utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('icon', models.ImageField(blank=True, upload_to=district.models.user.user_icon_upload_to)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('training_time', models.DateTimeField()),
                ('result_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('gen_file', models.CharField(max_length=128, unique=True)),
                ('icon', models.ImageField(blank=True, upload_to='icons/exercises')),
            ],
        ),
        migrations.CreateModel(
            name='Exo2Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('solve_percentage_req', models.FloatField(default=100.0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExoTest2Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_test_try', models.IntegerField(default=0)),
                ('nb_test_pass', models.IntegerField(default=0)),
                ('nb_train_try', models.IntegerField(default=0)),
                ('nb_train_pass', models.IntegerField(default=0)),
                ('exec_timeout', models.IntegerField(default=10)),
                ('exec_max_memory', models.IntegerField(default=-1)),
                ('exo2test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.exo2test')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('icon', models.ImageField(blank=True, upload_to='icons/groups')),
                ('register_key', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InspectorMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(blank=True, storage=toolbox.utils.utils.OverwriteStorage, upload_to=toolbox.utils.utils.upload_imagefield_to)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('icon', models.ImageField(blank=True, upload_to=toolbox.utils.utils.upload_imagefield_to)),
                ('default_code', models.TextField(blank=True)),
                ('language_program', models.CharField(default='None', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to='icons/tests')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_test_try', models.IntegerField(default=0)),
                ('solve_time', models.DateTimeField(auto_now_add=True)),
                ('solve_code', models.TextField()),
                ('solve_percentage', models.FloatField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.assessment')),
                ('exo_test2lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.exotest2lang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('exercises', models.ManyToManyField(to='district.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exotest2lang',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.language'),
        ),
        migrations.AddField(
            model_name='exo2test',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.testdc'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='insp_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.inspectormode'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='groups',
            field=models.ManyToManyField(to='district.groupdc'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.testdc'),
        ),
        migrations.AddField(
            model_name='userdc',
            name='groups',
            field=models.ManyToManyField(to='district.groupdc'),
        ),
        migrations.AddField(
            model_name='userdc',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
