# Generated by Django 4.0.4 on 2022-06-16 13:09
import os

from django.db import migrations

from toolbox.migration_tools.migration_group import group_migration
from toolbox.migration_tools.migration_inspect_mode import mode_migration
from toolbox.migration_tools.migration_language import language_migration


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(language_migration),
        migrations.RunPython(mode_migration),
        migrations.RunPython(group_migration),
    ]
