# Generated by Django 4.0.4 on 2022-06-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='gen_type_id',
            new_name='insp_mode_id',
        ),
        migrations.AlterField(
            model_name='inspectormode',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
