# Generated by Django 4.2.21 on 2025-06-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdc',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
