# Generated by Django 4.0.4 on 2022-06-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_rename_gen_type_id_exercise_insp_mode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdc',
            name='icon',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
