# Generated by Django 4.0.4 on 2022-05-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
