# Generated by Django 4.2.20 on 2025-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_alter_userdc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdc',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already in use'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
