# Generated by Django 4.0.4 on 2022-06-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_auto_20220616_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='solve_percentage',
            field=models.FloatField(default=0),
        ),
    ]
