# Generated by Django 4.0.4 on 2022-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_auto_20220616_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdc',
            name='email_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
