# Generated by Django 4.0.4 on 2022-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_userdc_email_confirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdc',
            old_name='email_confirmation',
            new_name='is_email_validated',
        ),
    ]
