# Generated by Django 4.0.4 on 2022-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0004_alter_exercise_icon_alter_groupdc_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdc',
            name='icon',
            field=models.FileField(blank=True, upload_to='toto/titi_%Y%m%d_%H%M%S/tata'),
        ),
    ]
