# Generated by Django 4.0.4 on 2022-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0005_alter_testdc_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='exercices',
            new_name='exercises',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/exercises'),
        ),
        migrations.AlterField(
            model_name='groupdc',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/groups'),
        ),
        migrations.AlterField(
            model_name='inspectormode',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/modes'),
        ),
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/languages'),
        ),
        migrations.AlterField(
            model_name='testdc',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/tests'),
        ),
        migrations.AlterField(
            model_name='userdc',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/users'),
        ),
    ]
