# Generated by Django 4.0.4 on 2022-06-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0006_rename_exercices_keyword_exercises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/exercises'),
        ),
        migrations.AlterField(
            model_name='groupdc',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/groups'),
        ),
    ]
