# Generated by Django 4.0.4 on 2022-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0007_alter_exercise_icon_alter_groupdc_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectormode',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/modes'),
        ),
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/languages'),
        ),
        migrations.AlterField(
            model_name='testdc',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/tests'),
        ),
        migrations.AlterField(
            model_name='userdc',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/users'),
        ),
    ]
