# Generated by Django 4.0.4 on 2022-06-13 08:35

import classes.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0008_alter_inspectormode_icon_alter_language_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectormode',
            name='icon',
            field=models.ImageField(blank=True, upload_to=classes.utils.utils.upload_imagefield_to),
        ),
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.ImageField(blank=True, upload_to=classes.utils.utils.upload_imagefield_to),
        ),
    ]
