EMAIL_HOST          = "smtp-xxxxx.mywebsite.com"
EMAIL_PORT          = 587
EMAIL_HOST_USER     = "myidentifier@mywebsite.net"
EMAIL_HOST_PASSWORD = "myPassword"
EMAIL_USE_TLS       = True
EMAIL_USE_SSL       = False
# EMAIL_TIMEOUT = ""
# EMAIL_SSL_KEYFILE = ""
# EMAIL_SSL_CERTFILE = ""
